### PR TITLE
SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @christopherbryanboyd  can you take a look at the failing tests?  I see this exception is swallowed by blade
```com.beust.jcommander.MissingCommandException: Expected a command, got -b```

**Comment by gamerson** [comment]
in the deployCOmmandTest

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by christopherbryanboyd** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/344. [See changes here.](https://github.com/christopherbryanboyd/liferay-blade-cli/compare/9b14dbe~1...9b14dbe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
